name: build

on:
  push:

env:
  OWNER: ${{ github.repository_owner }}
  FILE: proget
  IMAGE: ghcr.io/${{ github.repository_owner }}/proget

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  packages: write

jobs:

  linux:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    env:
      # TAG: linux
      TAG: latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Init
        run: ./bin/init.sh
        shell: bash

      - name: docker-config
        uses: containerbase/internal-tools@67c1778f7c7b48110e8278952e08b8b71e3ccedf # v3.4.20
        with:
          command: docker-config

      - name: Build the Docker image
        run: docker buildx bake --progress plain test

      - name: Test run
        run: docker compose --file docker-compose.test.yml run sut
        working-directory: ./linux
        env:
          IMAGE: ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/main'
        run: docker buildx bake build
